import { DocumentType, Status } from '../../common/constants';

export const customerSeedData = [
  {
    name: 'Jafet',
    lastName1: 'Grau',
    lastName2: null,
    document: '13632544',
    documentType: DocumentType.CUIL,
    email: null,
    phone: '+34 742 597 134',
    address: 'Via de Ceferino Muro 42 Apt. 06 , Huesca, 12784',
    status: Status.inactivo,
  },
  {
    name: 'Rosalina',
    lastName1: 'Gonzalo',
    lastName2: null,
    document: '26205084',
    documentType: DocumentType.CUIT,
    email: 'ubernat@jove-llabres.com',
    phone: '+34728 279 042',
    address: 'Camino de Adoración Cerdá 43 Apt. 77 , Palencia, 54768',
    status: Status.inactivo,
  },
  {
    name: 'Dolores',
    lastName1: 'Saez',
    lastName2: 'Fuster',
    document: '33244058',
    documentType: DocumentType.DNI,
    email: 'aranzazu10@gmail.com',
    phone: '+34 876 16 72 87',
    address: 'Ronda de Celso Vazquez 131 Apt. 69 , Cantabria, 17023',
    status: Status.inactivo,
  },
  {
    name: 'Santos',
    lastName1: 'Linares',
    lastName2: 'Arregui',
    document: '58084396',
    documentType: DocumentType.CUIL,
    email: 'lola29@hotmail.com',
    phone: '+34 726 04 25 21',
    address: 'Calle de Rico Fajardo 231, Melilla, 30128',
    status: Status.activo,
  },
  {
    name: 'Yaiza',
    lastName1: 'Dávila',
    lastName2: null,
    document: '37146559',
    documentType: DocumentType.CUIT,
    email: 'edmundomorera@jordan.net',
    phone: '+34738 65 97 00',
    address: 'Rambla de Camila Palomo 25, Baleares, 77290',
    status: Status.activo,
  },
  {
    name: 'Edgardo',
    lastName1: 'Mínguez',
    lastName2: 'Tamarit',
    document: '31789857',
    documentType: DocumentType.DNI,
    email: 'amadobarragan@beltran.es',
    phone: '+34742060408',
    address: 'Rambla Soraya Muro 23, Valladolid, 20705',
    status: Status.activo,
  },
  {
    name: 'Esperanza',
    lastName1: 'Bilbao',
    lastName2: 'Sáez',
    document: '74365871',
    documentType: DocumentType.CUIL,
    email: 'joaquinacano@lujan.com',
    phone: '+34 722011783',
    address: 'Urbanización Ani Pulido 88 Puerta 3 , Zamora, 71010',
    status: Status.activo,
  },
  {
    name: 'Magdalena',
    lastName1: 'Pagès',
    lastName2: 'Pinedo',
    document: '97318451',
    documentType: DocumentType.DNI,
    email: 'xjordan@gmail.com',
    phone: '+34 705 461 157',
    address: 'Acceso de Odalis Perales 20 Piso 3 , Las Palmas, 85820',
    status: Status.activo,
  },
  {
    name: 'Edu',
    lastName1: 'Lasa',
    lastName2: 'Guerra',
    document: '65188168',
    documentType: DocumentType.DNI,
    email: 'flora48@hotmail.com',
    phone: '+34 919735644',
    address: 'Cuesta Fulgencio Cueto 86 Puerta 7 , Badajoz, 74220',
    status: Status.inactivo,
  },
  {
    name: 'Rómulo',
    lastName1: 'Coloma',
    lastName2: 'Benavente',
    document: '4643761',
    documentType: DocumentType.DNI,
    email: 'bcarlos@donaire.com',
    phone: '+34748 094 349',
    address: 'Vial de Nayara Romero 48, Valencia, 83615',
    status: Status.inactivo,
  },
  {
    name: 'Virginia',
    lastName1: 'Montero',
    lastName2: 'Elías',
    document: '69928876',
    documentType: DocumentType.CUIT,
    email: 'fabianfolch@gmail.com',
    phone: '+34 746 79 91 53',
    address: 'Urbanización Norberto Torrent 949 Apt. 74 , Sevilla, 37127',
    status: Status.activo,
  },
  {
    name: 'Esperanza',
    lastName1: 'Castrillo',
    lastName2: 'Ibarra',
    document: '98440353',
    documentType: DocumentType.CUIT,
    email: 'cidclemente@yahoo.com',
    phone: '+34725 11 12 96',
    address: 'Pasaje de Artemio Hernandez 77 Puerta 8 , Murcia, 40632',
    status: Status.activo,
  },
  {
    name: 'Toni',
    lastName1: 'Segarra',
    lastName2: 'Miró',
    document: '94320198',
    documentType: DocumentType.CUIT,
    email: 'nildabuendia@gmail.com',
    phone: '+34727 36 75 49',
    address: 'Acceso Isidoro Tejada 47 Puerta 4 , Badajoz, 62298',
    status: Status.activo,
  },
  {
    name: 'Belén',
    lastName1: 'Cabrera',
    lastName2: null,
    document: '71274276',
    documentType: DocumentType.CUIL,
    email: 'tejerabelen@pineda-izaguirre.org',
    phone: '+34 738 733 728',
    address: 'Plaza Segismundo Llopis 975 Puerta 5 , Lleida, 42652',
    status: Status.inactivo,
  },
  {
    name: 'Elpidio',
    lastName1: 'Figueroa',
    lastName2: null,
    document: '53530729',
    documentType: DocumentType.DNI,
    email: 'jenny87@cervantes-viana.com',
    phone: '+34 615 18 14 67',
    address: 'Vial de Fausto Marquez 309, Burgos, 10497',
    status: Status.activo,
  },
  {
    name: 'Dafne',
    lastName1: 'Zapata',
    lastName2: null,
    document: '72816346',
    documentType: DocumentType.CUIL,
    email: 'trini80@gmail.com',
    phone: '+34 712 09 67 45',
    address: 'Callejón Rafa Solé 57, Burgos, 91770',
    status: Status.activo,
  },
  {
    name: 'Maxi',
    lastName1: 'Manzanares',
    lastName2: null,
    document: '95120969',
    documentType: DocumentType.CUIT,
    email: 'torreirma@campos.es',
    phone: '+34713 27 65 12',
    address: 'Calle Imelda Machado 89, Alicante, 82719',
    status: Status.activo,
  },
  {
    name: 'Cleto',
    lastName1: 'Planas',
    lastName2: 'Prieto',
    document: '67116948',
    documentType: DocumentType.DNI,
    email: null,
    phone: '+34 702914265',
    address: 'Pasaje Valentín Nogueira 7 Apt. 88 , Pontevedra, 25130',
    status: Status.inactivo,
  },
  {
    name: 'Nydia',
    lastName1: 'Cabo',
    lastName2: null,
    document: '51138019',
    documentType: DocumentType.CUIL,
    email: 'cuencacelia@ripoll.com',
    phone: '+34 701 32 14 73',
    address: 'Camino Mar Pombo 93, Guipúzcoa, 26523',
    status: Status.inactivo,
  },
  {
    name: 'Florinda',
    lastName1: 'Español',
    lastName2: 'España',
    document: '53794313',
    documentType: DocumentType.DNI,
    email: 'gabinobaez@azorin.com',
    phone: '+34993 01 11 35',
    address: 'Pasaje de Feliciano Fonseca 17 Apt. 87 , Palencia, 07684',
    status: Status.inactivo,
  },
];
